
service: tweetsheetexpress-api

provider:
  name: aws
  region: us-west-2
  runtime: nodejs6.10

functions:
  create:
    handler: sheets.create
    events:
      - http:
          method: POST
          path: sheets
          cors: true
